name: Build and test
on:
  pull_request: { }
  workflow_call: { }
  workflow_dispatch: { }
jobs:
  code-formatting:
    name: check code formatting
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Check format
        run: mvn spotless:check

      - name: Check license
        run: mvn license:check

  build-and-test-embedded:
    name: Run tests on ${{ matrix.os }}
    timeout-minutes: 15
    needs: code-formatting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        id: build
        run: mvn -B -U -pl "-:zeebe-process-test-qa-testcontainers" "-Dsurefire.rerunFailingTestsCount=5" clean install

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test Results ${{ matrix.os }}
          path: "*/target/surefire-reports/"
          retention-days: 7

  build-and-test-testcontainers:
    name: Run tests on ubuntu-latest using testcontainers
    timeout-minutes: 15
    needs: code-formatting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    env:
      IMAGE_NAME: "localhost:5000/qa-tests"
      TC_CLOUD_TOKEN: ${{ secrets.TC_CLOUD_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Package
        run: mvn -B -U clean package -DskipTests

      - name: Build engine docker container
        run: |
          cd engine-agent
          docker run --rm -d -p 5000:5000 --name registry registry:2
          docker build . -t ${{ env.IMAGE_NAME }}:testrun
          docker push ${{ env.IMAGE_NAME }}:testrun

      - name: Prepare Testcontainers Cloud agent
        if: env.TC_CLOUD_TOKEN != ''
        run : |
          curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_x86-64
          chmod +x agent
          ./agent --private-registry-url="http://localhost:5000" --private-registry-allowed-image-name-globs=*,*/* &
          ./agent wait

      - name: Update image tag in config
        run: |
          cd extension-testcontainer/src/main/resources
          sed -i '/container.image.name=/ s#=.*#=${{ env.IMAGE_NAME }}#' config.properties
          sed -i '/container.image.tag=/ s/=.*/=testrun/' config.properties
          cat config.properties
        env:
          IMAGE_NAME_KEY: container.image.name
          IMAGE_TAG_KEY: container.image.tag

      - name: Downgrade Java environment
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      # Deleting .mvn/jvm.config is a workaround for JDK8, which does not support the --add-exports options
      - name: Build
        id: build
        run: |
          rm .mvn/jvm.config
          mvn -B -U -pl ":zeebe-process-test-qa-testcontainers" -am "-Dsurefire.rerunFailingTestsCount=5" install -DskipChecks

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Unit Test Results Testcontainers
          path: "*/target/surefire-reports/"
          retention-days: 7


  # We need to upload the event file as an artifact in order to support publishing the results of
# forked repositories (https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches)
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
          retention-days: 1

