# If this workflow is triggered by a push to main, it deploys a SNAPSHOT
# If this workflow is triggered manually, it deploys a SNAPSHOT
# If this workflow is triggered by publishing a Release, it
#        deploys a RELEASE with the selected version
#        updates the project version by incrementing the patch version
#        commits the version update change to the repository's default branch (main).
name: Deploy artifacts
on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch: { }
jobs:
  test:
    uses: ./.github/workflows/build-test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    env:
      OWNER: "camunda"
      IMAGE_NAME: "zeebe-process-test-engine"
      TAG: "latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/common/github.com/actions/camunda/zeebe-process-test REGISTRY_HUB_DOCKER_COM_USR;
            secret/data/common/github.com/actions/camunda/zeebe-process-test REGISTRY_HUB_DOCKER_COM_PSW;
            secret/data/common/github.com/actions/camunda/zeebe-process-test ARTIFACTS_USR;
            secret/data/common/github.com/actions/camunda/zeebe-process-test ARTIFACTS_PSW;
            secret/data/common/github.com/actions/camunda-community-hub MAVEN_CENTRAL_DEPLOYMENT_USR;
            secret/data/common/github.com/actions/camunda-community-hub MAVEN_CENTRAL_DEPLOYMENT_PSW;
            secret/data/common/github.com/actions/camunda-community-hub MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE;
            secret/data/common/github.com/actions/camunda-community-hub MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC;

      - name: Set up Java environment
        uses: actions/setup-java@v3.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Build jar
        run: |
          mvn clean package -DskipTests -pl :zeebe-process-test-engine-agent -am

        # We build a docker image with a specific tag. There are 2 possible scenarios here.
        # 1. The workflow is triggered manually or by a change on the main branch. The tag should be 'latest'.
        # 2. The workflow is triggered by a new release. The tag should be the version of the release.
      - name: Build Docker image
        run: |
          if ! [ -z "${{ github.event.release.tag_name }}" ] && ! grep -q "$TAG" <<< "SNAPSHOT"; then
            TAG="${{ github.event.release.tag_name }}"
          fi
          cd engine-agent
          docker build . -t $IMAGE_NAME:$TAG

        # We push the docker image to dockerhub
      - name: Push Docker image
        run: |
          if ! [ -z "${{ github.event.release.tag_name }}" ] && ! grep -q "$TAG" <<< "SNAPSHOT"; then
            TAG="${{ github.event.release.tag_name }}"
          fi
          echo '${{ steps.secrets.outputs.REGISTRY_HUB_DOCKER_COM_PSW }}' | docker login -u '${{ steps.secrets.outputs.REGISTRY_HUB_DOCKER_COM_USR }}' --password-stdin
          echo $IMAGE_NAME
          echo $TAG
          IMAGE_ID=$OWNER/$IMAGE_NAME
          echo $IMAGE_ID
          docker tag $IMAGE_NAME:$TAG $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG

        # In extension-testcontainer we have a config file which contains the image tag. This is managed by maven and
        # maven will set this to the project version upon packaging the application (e.g. 1.4.0, 1.4.0-alpha1, etc.).
        # In the case this workflow is triggered by a change on the main branch we want this tag to be set to latest.
        # Maven would set it to a SNAPSHOT version in this case. Therefore, we need to manually set this tag to latest
        # in this step. This replaces the other value (${project.version}), so it doesn't get replaced by maven anymore.
      - name: Update tag in config
        if: github.ref == 'refs/head/main'
        run: |
          cd extension-testcontainer/src/main/resources
          sed -i '/container.image.tag=/ s:=.*:='$TAG':' config.properties
          cat config.properties

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
          passphrase: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}

        # In extension-testcontainer we have a config file which contains the image tag. This is managed by maven and
        # maven will set this to the project version in this step, unless the placeholder (${project.version}) has been
        # overridden by the "Update tag in config" step. This happens when the workflow is triggered by a change on the
        # main branch.
      - name: Build and deploy to Maven
        id: release
        uses: camunda-community-hub/community-action-maven-release@v1.0.13
        with:
          release-version: ${{ github.event.release.tag_name }}
          release-profile: community-action-maven-release
          nexus-usr: ${{ steps.secrets.outputs.ARTIFACTS_USR }}
          nexus-psw: ${{ steps.secrets.outputs.ARTIFACTS_PSW }}
          maven-usr: ${{ steps.secrets.outputs.MAVEN_CENTRAL_DEPLOYMENT_USR }}
          maven-psw: ${{ steps.secrets.outputs.MAVEN_CENTRAL_DEPLOYMENT_PSW }}
          maven-gpg-passphrase: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
          maven-url: s01.oss.sonatype.org
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach artifacts to GitHub Release (Release only)
        if: github.event.release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_name: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_content_type: application/zip
